import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  MessageSquarePlus,
  Database,
  FileSpreadsheet,
  Sparkles,
  Bot,
  ArrowRight,
  History,
  CheckCircle,
  TrendingUp,
} from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { chatApi } from '../api/chatApi';
import { ChatSession } from '../types/chat';
import { StateWrapper } from '../components/common/StateWrapper';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../components/ui/card';
import { Button } from '../components/ui/button';

export const DashboardPage: React.FC = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [sessions, setSessions] = useState<ChatSession[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [isError, setIsError] = useState<boolean>(false);
  const [error, setError] = useState<any>(null);

  const fetchSessions = async () => {
    setIsLoading(true);
    setIsError(false);
    try {
      const data = await chatApi.getSessions();
      setSessions(data);
    } catch (err) {
      setIsError(true);
      setError(err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchSessions();
  }, []);

  const handlePromptClick = async (question: string) => {
    try {
      const session = await chatApi.createSession({
        agent_type: 'sql',
        title: question.slice(0, 30) + '...',
      });
      navigate(`/chat/${session.id}?q=${encodeURIComponent(question)}`);
    } catch (err) {
      console.error('Failed to create session from prompt template:', err);
    }
  };

  const promptTemplates = [
    {
      title: 'Top Customer Revenue',
      prompt: 'Show me the top 10 customers by total rental payments in the pagila database.',
      agent: 'SQL RAG',
    },
    {
      title: 'Film Category Sales Breakdown',
      prompt: 'Calculate total revenue generated by film category and render a bar chart.',
      agent: 'SQL RAG',
    },
    {
      title: 'Monthly Rental Trends',
      prompt: 'What are the monthly rental volume trends over time?',
      agent: 'SQL RAG',
    },
    {
      title: 'CSV Sales Dataset Cleanup',
      prompt: 'Analyze messy sales dataset columns, handle missing values, and summarize top items.',
      agent: 'Pandas',
    },
  ];

  return (
    <div className="space-y-8 max-w-7xl mx-auto pb-12 animate-fade-in-up">
      {/* Welcome Banner Card */}
      <div className="relative p-8 rounded-3xl bg-space-surface/80 border border-violet-500/20 shadow-2xl shadow-violet-500/5 backdrop-blur-xl overflow-hidden glitter-container">
        {/* Top gradient glow line */}
        <div className="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-violet-500/50 to-transparent" />
        <div className="absolute right-0 top-0 w-96 h-96 bg-violet-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute left-1/3 bottom-0 w-64 h-64 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-violet-500/10 border border-violet-500/25 text-violet-300 text-xs font-semibold animate-breathe">
              <Sparkles className="w-3.5 h-3.5 text-violet-400" />
              <span>Enterprise AI Data Analyst Platform</span>
            </div>
            <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight font-heading">
              Welcome back, <span className="text-gradient-violet-cyan">{user?.username || 'Analyst'}</span>!
            </h1>
            <p className="text-sm text-slate-400 max-w-xl leading-relaxed">
              Ask natural-language questions to generate PostgreSQL queries, extract schemas, render Plotly charts, and analyze raw CSV spreadsheets.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-3 shrink-0">
            <Button
              variant="outline"
              onClick={() => navigate('/database')}
              leftIcon={<Database className="w-4 h-4 text-violet-400" />}
            >
              Database Explorer
            </Button>
            <Button
              onClick={() => navigate('/pandas')}
              leftIcon={<FileSpreadsheet className="w-4 h-4" />}
            >
              Upload CSV Dataset
            </Button>
          </div>
        </div>
      </div>

      {/* Metrics Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5 stagger-children">
        <Card glowColor="violet">
          <CardContent className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-violet-500/10 border border-violet-500/25 flex items-center justify-center text-violet-400">
              <Bot className="w-6 h-6" />
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 font-heading">
                Active AI Sessions
              </p>
              <p className="text-2xl font-extrabold text-white mt-0.5 font-heading">
                {sessions.length}
              </p>
            </div>
          </CardContent>
        </Card>

        <Card glowColor="emerald">
          <CardContent className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-emerald-500/10 border border-emerald-500/25 flex items-center justify-center text-emerald-400">
              <CheckCircle className="w-6 h-6" />
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 font-heading">
                Target Database
              </p>
              <p className="text-sm font-extrabold text-emerald-300 mt-1 font-mono">
                PostgreSQL Pagila
              </p>
            </div>
          </CardContent>
        </Card>

        <Card glowColor="cyan">
          <CardContent className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-2xl bg-cyan-500/10 border border-cyan-500/25 flex items-center justify-center text-cyan-400">
              <TrendingUp className="w-6 h-6" />
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 font-heading">
                Supported Engines
              </p>
              <p className="text-sm font-extrabold text-cyan-300 mt-1 font-heading">
                SQL RAG + Pandas Agent
              </p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Quick Prompt Templates */}
      <div className="space-y-4">
        <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2 font-heading">
          <Sparkles className="w-5 h-5 text-violet-400" />
          Suggested Prompt Starter Templates
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {promptTemplates.map((template, i) => (
            <div
              key={i}
              onClick={() => handlePromptClick(template.prompt)}
              className="p-5 rounded-2xl bg-space-surface/80 border border-white/[0.07] hover:border-violet-500/40 cursor-pointer transition-all duration-300 hover-lift shadow-lg group relative overflow-hidden"
            >
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-bold text-violet-300 font-mono">
                  {template.title}
                </span>
                <span className="text-[10px] text-slate-400 bg-space-elevated px-2 py-0.5 rounded border border-white/[0.05] font-mono">
                  {template.agent}
                </span>
              </div>
              <p className="text-xs text-slate-400 leading-relaxed group-hover:text-white transition-colors">
                "{template.prompt}"
              </p>
              <div className="flex items-center gap-1 text-[11px] font-semibold text-violet-400 mt-3 group-hover:translate-x-1 transition-transform duration-200">
                <span>Run Prompt Query</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Recent Sessions List */}
      <div className="space-y-4 pt-4">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2 font-heading">
            <History className="w-5 h-5 text-cyan-400" />
            Recent Conversational Sessions
          </h2>
        </div>

        <StateWrapper
          isLoading={isLoading}
          isError={isError}
          error={error}
          isEmpty={sessions.length === 0}
          onRetry={fetchSessions}
          isRetrying={isLoading}
          skeletonVariant="list"
          skeletonCount={3}
          emptyTitle="No recent chat sessions"
          emptyDescription="Start a new SQL or Pandas analysis to build your history."
        >
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {sessions.slice(0, 6).map((session) => (
              <div
                key={session.id}
                onClick={() => navigate(`/chat/${session.id}`)}
                className="p-5 rounded-2xl bg-space-surface/60 border border-white/[0.07] hover:border-violet-500/40 cursor-pointer transition-all duration-300 hover-lift shadow-md group relative overflow-hidden"
              >
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-violet-300 bg-violet-500/10 px-2 py-0.5 rounded border border-violet-500/20 font-mono">
                    {session.agent_type.toUpperCase()} AGENT
                  </span>
                  <span className="text-[10px] text-slate-500">
                    {new Date(session.created_at).toLocaleDateString()}
                  </span>
                </div>
                <h3 className="text-sm font-bold text-slate-200 group-hover:text-violet-300 transition-colors truncate font-heading">
                  {session.title || 'Untitled Session'}
                </h3>
                <p className="text-xs text-slate-500 mt-1">
                  {session.messages?.length || 0} messages exchanged
                </p>
              </div>
            ))}
          </div>
        </StateWrapper>
      </div>
    </div>
  );
};
